<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MaterialDesign.DialogPlus" Version="1.1.0" />
    <PackageReference Include="MaterialDesignInXamlToolkitAddOns" Version="0.0.63" />
    <PackageReference Include="MaterialDesignThemes.Prism" Version="0.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CGMAnalyzerCore\CGMAnalyzerCore.csproj" />
  </ItemGroup>

</Project>
