<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <EnableWindowsFormsCompatibility>true</EnableWindowsFormsCompatibility>
	  <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotLiquid" Version="2.3.197" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\AttributeCommands\" />
    <Folder Include="Commands\ExternalCommands\" />
    <Folder Include="Commands\PictureCommands\" />
  </ItemGroup>

</Project>
